name: Code Tests

on:
  pull_request:

jobs:
  UCI:
    name: UCI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate code with UCI
        uses: meltingcore/uci@v0
